CREATE TABLE `REGUFEE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_RAW` varchar(150) DEFAULT NULL,
  `ESCUELA_NAME` varchar(150) DEFAULT NULL,
  `LATITUDE` double DEFAULT NULL,
  `LONGITUDE` double DEFAULT NULL,
  `CONDICION` varchar(50) DEFAULT NULL,
  `COMMENT_RAW` varchar(150) DEFAULT NULL,
  `COMMENT_PARSE` varchar(100) DEFAULT NULL,
  `MUNICIPIO` varchar(100) DEFAULT NULL,
  `CAPACIDAD` int(11) DEFAULT NULL,
  `ADDRESS_1_REF_OLD` varchar(200) DEFAULT NULL,
  `ADDRESS_2_REF_NEW` varchar(200) DEFAULT NULL,
  `ZONA_AEMEA` int(11) DEFAULT NULL,
  `TELEFONO` varchar(15) DEFAULT NULL,
  `CONDITION_CATEGORY` varchar(50) DEFAULT NULL,
  `NAME` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=512 DEFAULT CHARSET=latin1;



CREATE TABLE `COMMENT_TOKENIZER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMMENT_STR` varchar(100) DEFAULT NULL,
  `COMMENT_CATEGORY` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=96 DEFAULT CHARSET=latin1;